#!/bin/sh
ssh ubuntu@3.134.198.50 <<EOF
    cd /var/www/dev/rp3_test_server_coupang_eats_coogie		
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 16.8.0
    npm install
    npm install -g pm2
    pm2 restart ecosystem.config.js
    exit
EOF