#!/bin/sh
ssh ubuntu@3.134.198.50 <<EOF
    cd /var/www/dev/rp3_test_server_coupang_eats_coogie
    rm -rf node_modules		
    git pull origin master
    npm install
    pm2 start npm -- run dev --watch
    exit
EOF